Added F1 score, Accuracy and Balanced Accuracy from ROC
haesleinhuepf/the-segmentation-game pull request #3
Opened 2022-05-31 12:06 UTC by martinschatz-cz

Some metrics (such as accuracy) do not always make sense. Segmentation is an excellent example of when to select the proper metrics carefully. Balanced accuracy and F1 Score are examples of better metrics for imbalanced sets.

2022-05-31 13:25 UTC, haesleinhuepf requested changes
Awesome, thanks for this @martinschatz-cz !

I'd merge it if you add a section for these measures in the readme. Especially describe when these measures make sense. 
https://github.com/haesleinhuepf/the-segmentation-game/blob/main/README.md#metrics

Furthermore, if you could add a test here that would be great as well:
https://github.com/haesleinhuepf/the-segmentation-game/blob/main/src/the_segmentation_game/_tests/test_metrics.py

Thanks!

Robert

2022-06-01 12:07 UTC, martinschatz-cz commented
I will start working on it, thanks for the feedback. I would like to add a bunch more things around ROC. But for now, I will start with this.

Martin

2022-06-03 18:18 UTC, martinschatz-cz commented
Hi @haesleinhuepf,

I have added text around ROC metrics and tests. I will want to add more (rest of ROC), a bit more detailed explanations, and some pitfalls. I just want to get hang of this (mainly the test) before I start adding more :).

Let me know what I can improve.
Martin

2022-06-04 07:32 UTC, haesleinhuepf commented on README.md
> +Other ROC metrics will be implemented soon...
```suggestion

```

2022-06-04 07:33 UTC, haesleinhuepf approved these changes
Hey Martin @martinschatz-cz ,

this is so gool! Thanks so much!

2022-06-04 07:36 UTC, merged